package com.only.engine.constants;

import com.only.engine.enums.HttpStatus;

public interface StandardCode {

    /**
     * 正常执行返回
     */
    int SUCCESS = HttpStatus.OK.getValue() * 100;

    /**
     * 用户端异常
     */
    interface UserSide {
        int EXCEPTION = 40000;
        int REGISTER_EXCEPTION = 40100;
        int NOT_AGREE_PRIVACY_AGREEMENT = REGISTER_EXCEPTION + 1;

        int USERNAME_INVALID = 40110;
        int USERNAME_ALREADY_EXISTS = USERNAME_INVALID + 1;
        int USERNAME_CONTAIN_SENSITIVE_WORDS = USERNAME_ALREADY_EXISTS + 1;
        int USERNAME_CONTAIN_SPECIAL_CHAR = USERNAME_CONTAIN_SENSITIVE_WORDS + 1;

        int PWD_INVALID = 40120;
        int PWD_LENGTH_INSUFFICIENT = PWD_INVALID + 1;
        int PWD_STRENGTH_INSUFFICIENT = PWD_LENGTH_INSUFFICIENT + 1;

        int VERIFICATION_CODE_INVALID = 40130;
        int VERIFICATION_CODE_SMS_INVALID = VERIFICATION_CODE_INVALID + 1;
        int VERIFICATION_CODE_EMAIL_INVALID = VERIFICATION_CODE_SMS_INVALID + 1;

        int VERIFY_BASIC_INFO_INVALID = 40150;
        int VERIFY_MOBILE_FORMAT_INVALID = VERIFY_BASIC_INFO_INVALID + 1;
        int VERIFY_ADDRESS_FORMAT_INVALID = VERIFY_MOBILE_FORMAT_INVALID + 1;
        int VERIFY_EMAIL_FORMAT_INVALID = VERIFY_ADDRESS_FORMAT_INVALID + 1;

        int LOGIN_EXCEPTION = 40200;
        int LOGIN_ACCOUNT_NOT_EXIST = LOGIN_EXCEPTION + 1;
        int LOGIN_ACCOUNT_FREEZE = LOGIN_ACCOUNT_NOT_EXIST + 1;
        int LOGIN_ACCOUNT_DISABLED = LOGIN_ACCOUNT_FREEZE + 1;
        int LOGIN_ACCOUNT_LOCKED = LOGIN_ACCOUNT_DISABLED + 1;
        int LOGIN_ACCOUNT_ALREADY_LOGIN = LOGIN_ACCOUNT_LOCKED + 1;
        int LOGIN_ACCOUNT_FIRST_LOGIN_NEED_CHANGE_PWD = LOGIN_ACCOUNT_ALREADY_LOGIN + 1;

        int LOGIN_PWD_NOT_MATCH = 40210;
        int LOGIN_PWD_NOT_MATCH_EXCEEDS_LIMIT = LOGIN_PWD_NOT_MATCH + 1;

        int LOGIN_TOKEN_EXCEPTION = 40230;
        int LOGIN_TOKEN_INVALID = LOGIN_TOKEN_EXCEPTION + 1;
        int LOGIN_TOKEN_EXPIRED = LOGIN_TOKEN_INVALID + 1;

        int LOGIN_VERIFICATION_CODE_NOT_MATCH = 40240;
        int LOGIN_VERIFICATION_CODE_NOT_MATCH_EXCEEDS_LIMIT = 40241;

        int UNAUTHORIZED = 40300;
        int UNAUTHORIZED_ACCESS_DENIED = UNAUTHORIZED + 1;
        int UNAUTHORIZED_AUTHORIZATION_EXPIRED = UNAUTHORIZED_ACCESS_DENIED + 1;
        int UNAUTHORIZED_BLACKLIST_USER = UNAUTHORIZED_AUTHORIZATION_EXPIRED + 1;
        int UNAUTHORIZED_TOKEN_INVALID = UNAUTHORIZED_BLACKLIST_USER + 1;

        int REQUEST_PARAMETER_EXCEPTION = 40400;
        int REQUEST_PARAMETER_REQUIRED_IS_NOT_NULL = REQUEST_PARAMETER_EXCEPTION + 1;
        int REQUEST_PARAMETER_OUT_OF_ALLOWED_RANGE = REQUEST_PARAMETER_REQUIRED_IS_NOT_NULL + 1;
        int REQUEST_PARAMETER_FORMAT_NOT_MATCH = REQUEST_PARAMETER_OUT_OF_ALLOWED_RANGE + 1;
        int REQUEST_PARAMETER_AMOUNT_EXCEEDS_LIMIT = REQUEST_PARAMETER_FORMAT_NOT_MATCH + 1;
        int REQUEST_PARAMETER_QUANTITY_EXCEEDS_LIMIT = REQUEST_PARAMETER_AMOUNT_EXCEEDS_LIMIT + 1;
        int REQUEST_PARAMETER_BATCH_QUANTITY_EXCEEDS_LIMIT = REQUEST_PARAMETER_QUANTITY_EXCEEDS_LIMIT + 1;
        int REQUEST_PARAMETER_JSON_PARSE_FAILED = REQUEST_PARAMETER_BATCH_QUANTITY_EXCEEDS_LIMIT + 1;
        int REQUEST_PARAMETER_USER_INPUT_INVALID = REQUEST_PARAMETER_JSON_PARSE_FAILED + 1;
        int REQUEST_PARAMETER_USER_OPERATE_EXCEPTION = REQUEST_PARAMETER_USER_INPUT_INVALID + 1;

        int REQUEST_EXCEPTION = 40500;
        int REQUEST_TIMES_EXCEEDS_LIMIT = REQUEST_EXCEPTION + 1;
        int REQUEST_CONCURRENT_EXCEEDS_LIMIT = REQUEST_TIMES_EXCEEDS_LIMIT + 1;
        int REQUEST_WAIT_FOR_OPERATION = REQUEST_CONCURRENT_EXCEEDS_LIMIT + 1;
        int REQUEST_WEB_SOCKET_CONNECT_EXCEPTION = REQUEST_WAIT_FOR_OPERATION + 1;
        int REQUEST_WEB_SOCKET_DISCONNECT = REQUEST_WEB_SOCKET_CONNECT_EXCEPTION + 1;
        int REQUEST_REPEAT = REQUEST_WEB_SOCKET_DISCONNECT + 1;

        int UPLOAD_EXCEPTION = 40600;
        int UPLOAD_FILE_TYPE_NOT_MATCH = UPLOAD_EXCEPTION + 1;
        int UPLOAD_FILE_TOO_LARGE = UPLOAD_FILE_TYPE_NOT_MATCH + 1;
        int UPLOAD_IMG_TOO_LARGE = UPLOAD_FILE_TOO_LARGE + 1;
        int UPLOAD_VIDEO_TOO_LARGE = UPLOAD_IMG_TOO_LARGE + 1;
        int UPLOAD_COMPRESSED_FILE_TOO_LARGE = UPLOAD_VIDEO_TOO_LARGE + 1;
    }

    /**
     * 系统错误
     */
    interface SystemSide {
        int EXCEPTION = 50000;
        int EXECUTION_TIMEOUT = 50100;
        int RESOURCE_EXCEPTION = 50200;
        int OUT_OF_HARD_DISK = RESOURCE_EXCEPTION + 1;
        int OUT_OF_MEMORY = OUT_OF_HARD_DISK + 1;
    }

    /**
     * 第三方服务错误
     */
    interface ThirdParty {
        int EXCEPTION = 60000;

        int RPC_EXCEPTION = 60100;
        int RPC_SERVICE_NOT_FOUND = RPC_EXCEPTION + 1;
        int RPC_SERVICE_INTERFACE_NOT_FOUND = RPC_SERVICE_NOT_FOUND + 1;
        int RPC_EXECUTION_TIMEOUT = RPC_SERVICE_INTERFACE_NOT_FOUND + 1;

        int CACHE_SERVICE_EXCEPTION = 60200;
        int CACHE_KEY_LENGTH_EXCEEDS_LIMIT = CACHE_SERVICE_EXCEPTION + 1;
        int CACHE_VALUE_LENGTH_EXCEEDS_LIMIT = CACHE_KEY_LENGTH_EXCEEDS_LIMIT + 1;
        int CACHE_STORAGE_CAPACITY_IS_FULL = CACHE_VALUE_LENGTH_EXCEEDS_LIMIT + 1;
        int CACHE_UNSUPPORTED_DATA_FORMAT = CACHE_STORAGE_CAPACITY_IS_FULL + 1;
        int CACHE_SERVICE_TIMEOUT = CACHE_UNSUPPORTED_DATA_FORMAT + 1;

        int DATABASE_EXCEPTION = 60300;
        int DATABASE_SERVICE_TIMEOUT = DATABASE_EXCEPTION + 1;
        int DATABASE_TABLE_NOT_EXIST = DATABASE_SERVICE_TIMEOUT + 1;
        int DATABASE_COLUMN_NOT_EXIST = DATABASE_TABLE_NOT_EXIST + 1;
        int DATABASE_DEADLOCK = DATABASE_COLUMN_NOT_EXIST + 1;
        int DATABASE_PRIMARY_KEY_CONFLICT = DATABASE_DEADLOCK + 1;
        int DATABASE_MULTI_TABLE_ASSOCIATION_EXIST_SAME_COLUMNS_NAME = DATABASE_PRIMARY_KEY_CONFLICT + 1;
        int DATABASE_BAD_SQL_GRAMMAR = DATABASE_MULTI_TABLE_ASSOCIATION_EXIST_SAME_COLUMNS_NAME + 1;

        int MQ_EXCEPTION = 60400;
        int MQ_DELIVERY_EXCEPTION = MQ_EXCEPTION + 1;
        int MQ_CONSUME_EXCEPTION = MQ_DELIVERY_EXCEPTION + 1;
        int MQ_SUBSCRIPTION_EXCEPTION = MQ_CONSUME_EXCEPTION + 1;
        int MQ_GROUP_NOT_FOUND = MQ_SUBSCRIPTION_EXCEPTION + 1;
        int MQ_DELIVERY_TIMEOUT = MQ_GROUP_NOT_FOUND + 1;

        int CONFIG_SERVICE_EXCEPTION = 60500;
        int CONFIG_SERVICE_TIMEOUT = CONFIG_SERVICE_EXCEPTION + 1;

        int NOTICE_SERVICE_EXCEPTION = 60600;
        int NOTICE_SERVICE_SMS_NOTICE_EXCEPTION = NOTICE_SERVICE_EXCEPTION + 1;
        int NOTICE_SERVICE_VOICE_NOTICE_EXCEPTION = NOTICE_SERVICE_SMS_NOTICE_EXCEPTION + 1;
        int NOTICE_SERVICE_EMAIL_EXCEPTION = NOTICE_SERVICE_VOICE_NOTICE_EXCEPTION + 1;

        int DISASTER_RECOVERY_EXCEPTION = 60700;
        int DISASTER_RECOVERY_RATE_LIMIT = DISASTER_RECOVERY_EXCEPTION + 1;
        int DISASTER_RECOVERY_DEGRADED = DISASTER_RECOVERY_RATE_LIMIT + 1;
    }
}
